"""Criando campo em produto para imagem

Revision ID: 0acbd3d36af2
Revises: 7f0c9bb8af81
Create Date: 2025-11-06 20:24:58.915967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0acbd3d36af2'
down_revision: Union[str, Sequence[str], None] = '7f0c9bb8af81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'image')
    # ### end Alembic commands ###
