"""Criando relacionamento entre produtos e empresas

Revision ID: 4bc20e11a183
Revises: 613cbdd126d3
Create Date: 2025-10-24 11:57:23.565189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc20e11a183'
down_revision: Union[str, Sequence[str], None] = '613cbdd126d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('id_empresas', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_produtos_empresas', 'produtos', 'empresas', ['id_empresas'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_produtos_empresas', 'produtos', type_='foreignkey')
    op.drop_column('produtos', 'id_empresas')
    # ### end Alembic commands ###
