"""Criando tabelas de Estoque e movimentações e retirando coluna de quantidade e custo_und de produtos

Revision ID: 594cad3bd9f6
Revises: 76e88981826b
Create Date: 2025-10-15 17:58:18.711298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '594cad3bd9f6'
down_revision: Union[str, Sequence[str], None] = '76e88981826b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_produtos', sa.Integer(), nullable=False),
    sa.Column('quantidade_disponivel', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_produtos'], ['produtos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentacoes_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_produtos', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('entrada', 'saida', 'outro', name='movementtypesenum'), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_und', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_produtos'], ['produtos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('produtos', 'quantidade')
    op.drop_column('produtos', 'custo_und')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('custo_und', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('produtos', sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('movimentacoes_estoque')
    op.drop_table('estoque')
    # ### end Alembic commands ###
