"""Renomeando coluna de titulo de produto para nome

Revision ID: 76e88981826b
Revises: fe954278889f
Create Date: 2025-10-15 14:01:00.879150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76e88981826b'
down_revision: Union[str, Sequence[str], None] = 'fe954278889f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('nome', sa.String(), nullable=False))
    op.drop_column('produtos', 'titulo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('titulo', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('produtos', 'nome')
    # ### end Alembic commands ###
