"""Criando coluna de estoque ideal em estoque

Revision ID: 7f0c9bb8af81
Revises: 19554abf6ff7
Create Date: 2025-11-04 12:29:47.362402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0c9bb8af81'
down_revision: Union[str, Sequence[str], None] = '19554abf6ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estoque', sa.Column('estoque_ideal', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estoque', 'estoque_ideal')
    # ### end Alembic commands ###
