"""Retirando status de produtos2

Revision ID: 8463f6e809a8
Revises: f315243d4591
Create Date: 2025-10-15 13:54:21.834791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8463f6e809a8'
down_revision: Union[str, Sequence[str], None] = 'f315243d4591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
