"""Invertendo coluna custo médio

Revision ID: 865fad7d3aac
Revises: d3ed1f6af0f5
Create Date: 2025-10-15 18:57:28.339810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '865fad7d3aac'
down_revision: Union[str, Sequence[str], None] = 'd3ed1f6af0f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estoque', sa.Column('custo_medio', sa.Float(), nullable=False))
    op.drop_column('movimentacoes_estoque', 'custo_medio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimentacoes_estoque', sa.Column('custo_medio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('estoque', 'custo_medio')
    # ### end Alembic commands ###
