"""Criando relacionamento empresa e documentos

Revision ID: b049a84756eb
Revises: d831fdd46e12
Create Date: 2025-10-24 12:19:57.553151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b049a84756eb'
down_revision: Union[str, Sequence[str], None] = 'd831fdd46e12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos', sa.Column('id_empresas', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_documentos_empresas', 'documentos', 'empresas', ['id_empresas'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_documentos_empresas', 'documentos', type_='foreignkey')
    op.drop_column('documentos', 'id_empresas')
    # ### end Alembic commands ###
