"""Criando tabela de documentos

Revision ID: b4fceacdf2c3
Revises: 34e8a71c5540
Create Date: 2025-09-24 10:35:45.543115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4fceacdf2c3'
down_revision: Union[str, Sequence[str], None] = '34e8a71c5540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extracted', sa.Boolean(), nullable=False),
    sa.Column('document_path', sa.String(), nullable=False),
    sa.Column('extract_result', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
