"""Adicionando coluna de custo_medio em MovimentacoesEstoque

Revision ID: d3ed1f6af0f5
Revises: 594cad3bd9f6
Create Date: 2025-10-15 18:48:07.678593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ed1f6af0f5'
down_revision: Union[str, Sequence[str], None] = '594cad3bd9f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimentacoes_estoque', sa.Column('custo_medio', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movimentacoes_estoque', 'custo_medio')
    # ### end Alembic commands ###
