"""Criando relacionamento empresa e usuário

Revision ID: d831fdd46e12
Revises: 4bc20e11a183
Create Date: 2025-10-24 12:15:58.526635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd831fdd46e12'
down_revision: Union[str, Sequence[str], None] = '4bc20e11a183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('produtos', 'id_empresas',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('usuarios', sa.Column('id_empresas', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_usuarios_empresas', 'usuarios', 'empresas', ['id_empresas'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_usuarios_empresas', 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'id_empresas')
    op.alter_column('produtos', 'id_empresas',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
