"""Corrigindo tabela Document

Revision ID: dd9d9942870a
Revises: b4fceacdf2c3
Create Date: 2025-09-24 10:43:05.166725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd9d9942870a'
down_revision: Union[str, Sequence[str], None] = 'b4fceacdf2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'extract_result',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'extract_result',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
