"""Renomeando coluna de preco/custo_und

Revision ID: fe954278889f
Revises: 8463f6e809a8
Create Date: 2025-10-15 13:57:01.933967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe954278889f'
down_revision: Union[str, Sequence[str], None] = '8463f6e809a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('custo_und', sa.Float(), nullable=False))
    op.drop_column('produtos', 'preco_custo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('preco_custo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('produtos', 'custo_und')
    # ### end Alembic commands ###
